[features]
seeds = true
skip-lint = false
[programs.localnet]
auction = "39Cadm14PBnnAJ1LZA61v6zFXT9PNHrhKe9dDd2yg6un"
crowdfund = "8Bk7qQpQxqBz5XVX3LqV3vbpnNuZLhCnKq316UHThMHV"
escrow = "E7zX6apL8gud4oaHNU7gnD5akFnsZDsgcdNupadQvXXb"
htlc = "8kEhcRuAY94LejWbHkNtyS854NULabvDqL65qGoiF7VV"
oracle_bet = "Af66eBB9urMrYPgLR3RKBhyrQd5HWj3cYXC1nNUe2ma5"
payment_splitter = "2NpQpiMnHxzpYrtixekkjhbbkTREzFMg5mn6U66YAGfT"
simple_transfer = "GTqxqnSdEu5SjyhGjfAUvozmojYSxdE3uSPr6u9HYkqJ"
simple_wallet = "KpUxvh3VECWL7eX6j3hZ8kwD9knm25KfFCk9yUSxX3U"
storage = "2ZE5N8rTU2S2GUuQGX8ZsBAraByUqD37hYP8pz1hYLLJ"
tiny_amm = "ADY3EuA5hCthUru7JDWrTB1CqqxZxthZGWmvYGUw96rn"
token_transfer = "CxkwtHKHwiLRHZgPVrjc2QALiiCEK2xTu25rN5wWh9Fc"
vault = "7BEre5a4UcJpNUzmoJvxUcWpaw4LrYE8pVhmLxWDrqsS"
vesting = "FvMZMkWVuSqmRkH3T31PQXd9cmzNNQUCTDzMcAmQQFW8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vtkachenko/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_auction = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/auction.ts"
test_crowdfund = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/crowdfund.ts"
test_escrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/escrow.ts"
test_htlc = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/htlc.ts"
test_oracle_bet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_oracle_bet.ts"
test_payment_splitter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/payment_splitter.ts"
test_simple_transfer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/simple_transfer.ts"
test_simple_wallet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/simple_wallet.ts"
test_storage = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/storage.ts"
test_tiny_amm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tiny_amm.ts"
test_token_transfer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token_transfer.ts"
test_vault = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vault.ts"
test_vesting = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vesting.ts"
