[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.10.0"
solana-program = "1.16.24"

[lib]
crate-type = ["cdylib", "lib"]
